version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DargLine="-Dci-server=true"
  post_build:
    commands:
      - echo Build completed on `date`
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  files:
    - template-export.yml
  discard-paths: yes
