AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  TriggerNotification:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Wecky-NotifyUser
      Handler: de.smartsquare.wecky.NotificationHandler
      CodeUri: target/wecky-notify-1.0.jar
      Environment:
        Variables:
          DYNDB_LOCAL: ''
          S3_LOCAL: ''
          SES_LOCAL: ''
      Runtime: java8
      Timeout: 180
      MemorySize: 512
      Role: arn:aws:iam::960341205924:role/wecky-notify-lambda
      Events:
        UploadedScreenshot:
          Type: S3
          Properties:
            Bucket: !Ref WeckyScreens
            Events: s3:ObjectCreated:*
  WeckyScreens:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'wecky-screens'
