AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  TriggerNotification:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Wecky-NotifyUser
      Handler: de.smartsquare.wecky.NotificationHandler
      Runtime: java8
      Timeout: 180
      MemorySize: 512
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
